name = "chatroom"
main = "src/index.ts"
compatibility_date = "2024-04-05"

[assets]
directory = "./public"

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[d1_databases]]
binding = "DB"
database_name = "user-db"
database_id = "fd14d704-f266-41ff-8c40-4b77e6cac0be"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]

[observability.logs]
enabled = true
invocation_logs = true


[[r2_buckets]]
binding = "FILE_SHARE"
bucket_name = "chatroom-files"
